name: "Phpstan"

on:
  pull_request:

  push:
    branches: ["*"]

jobs:
  build:
    name: "Phpstan"
    uses: contributte/.github/.github/workflows/phpstan.yml@master
    with:
      composer: "composer remove typertion/generator && composer update --no-interaction --no-progress --prefer-dist --prefer-stable"
