name: "Nette Tester"

on:
  pull_request:

  push:
    branches: ["*"]

jobs:
  build81:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.1"
      makefile: "test"

  build80:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.0"
      makefile: "test"

  build74:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "7.4"
      makefile: "test"
