name: "Nette Tester"

on:
  pull_request:

  push:
    branches: ["*"]

jobs:
  build81:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.1"
      makefile: "test"
      composer: "composer remove typertion/generator --dev && composer update --no-interaction --no-progress --prefer-dist --prefer-stable"

  build80:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.0"
      makefile: "test"
      composer: "composer remove typertion/generator --dev && composer update --no-interaction --no-progress --prefer-dist --prefer-stable"

  build74:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "7.4"
      makefile: "test"
      composer: "composer remove typertion/generator --dev && composer update --no-interaction --no-progress --prefer-dist --prefer-stable"
